server:
    port: 9090

spring:
    datasource:
        beanPath: com.doraemon.base.dao.models
        mapperXmlPath: classpath:mapper/*.xml
        mapperPath: com.doraemon.base.dao.mapper
        master:
            name: ReadAndWrite
            url: jdbc:mysql://10.28.100.81:3306/jskj_gzw_kf?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root123
        slave1:
            name: ReadAndWrite
            url: jdbc:mysql://10.28.100.81:3306/jskj_gzw_cs?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root123

mail:
    smtpHost: smtp.163.com
#    smtpPort:
    account: jishitech666@163.com
    passwd: jishitech2017
#    from: jishitech666@163.com
#    to:
#    cc:
#    bcc:
#    ssl:
#     notSave:
#    savePath:

redis:
    host: 10.10.20.206
    port: 6381
# password: aaa
#  sentinel:
#    master: 192.168.81.13
#    nodes: 1
# pool:
#   max-active: 1
#   max-wait: 1
#   max-idle: 3
#   min-idle: 5
#   ssl: false
#   port: 3306
#   timeout: 343
#   url: 3443
#   database: 0
#   cluster:
#     max-redirects: fd
#     nodes: fds

