server:
    port: 9090

spring:
    datasource:
        beanPath: com.doraemon.baseTest.dao.models
        mapperXmlPath: classpath:mapper/*.xml
        mapperPath: com.doraemon.baseTest.dao.mapper
        master:
            name: ReadAndWrite
            url: jdbc:mysql://182.92.78.118:3306/his?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root
        slave1:
            name: ReadAndWrite
            url: jdbc:mysql://182.92.78.118:3306/his?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root

redis:
    host: r-wz911707093dd3a4.redis.rds.aliyuncs.com
    port: 6379
    password: Jskj1010
    database: 0

