server:
    port: 9090

spring:
    datasource:
        beanPath: com.doraemon.baseTest.dao.models
        mapperXmlPath: classpath:mapper/*.xml
        mapperPath: com.doraemon.baseTest.dao.mapper
        master:
            name: ReadAndWrite
            url: jdbc:mysql://10.28.100.81:3306/jskj_gzw_kf?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root123
        slave1:
            name: ReadAndWrite
            url: jdbc:mysql://10.28.100.81:3306/jskj_gzw_cs?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root123

