server:
   port: 50002
spring:
   cloud:
       config:
           server:
               svn:
                   uri: svn://192.168.81.14/jishitech/branches/jishitech-datacenter/src/main/resources




